name: tekyz_notification
description: "A reminder through notification app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^16.2.0
  flutter_timezone: ^1.0.8
  http: ^1.1.2
  image: ^4.1.3
  path_provider: ^2.1.1
  device_info_plus: ^9.1.1
  fluttertoast: ^8.2.4
  timezone: ^0.9.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
